const ADD_CONTACT = "ADD_CONTACT";
const EDIT_CONTACT = "EDIT_CONTACT";
const DELETE_CONTACT = "DELETE_CONTACT";
const GET_CONTACTS = "GET_CONTACTS";
const CONTACT_LOADING = "CONTACT_LOADING";
export {
  ADD_CONTACT,
  EDIT_CONTACT,
  DELETE_CONTACT,
  GET_CONTACTS,
  CONTACT_LOADING
};
